baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Style Thoughts by Rita"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "styletalk"
name = "Consultations"
weight = "3"
[[menu.main]]
URL = "blog"
name = "Style Thoughts"
weight = 3
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Rita"
description = "Style Thoughts by Rita"
[params.banner]
heading = ""
image = "/images/blue-and-white-professional-business-blog-banner.png"
[params.blog]
heading = "Style as self-expression, storytelling, pleasure, and play. \nBook a style talk with me or learn from me in my blog."
[params.call_to_action]
button_label = "Learn More!"
button_url = "styletalks"
content = "I offer 60 minute style consultations to help you see yourself clearly, shop with ease, and express your unique beauty to the world. "
enable = true
title = "Book your \"Style Talk with Rita\""
[params.footer]
address = "https://www.youtube.com/channel/UCQ8aepOZG20AZTyZLwRuocQ"
content = "My name is Rita and I am a style thinker, content creator, and style guide. Read about my work here or watch my YT channel!"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = ""
title = "Style Thoughts by Rita"
[params.gallery]
enable = false
gallery_item = []
[params.social]
email = "hello@stylethoughtsbyrita.com"
facebook = "#"
instagram = "@stylethoughtsbyrita"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
